using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class musicplayer : MonoBehaviour
{
    private static musicplayer instance = null;

    public static musicplayer Instance
    {
        get
        {
            return instance;
        }
    }
    void Start()
    {

    }

    void Awake()
    {
        if (instance != null && instance != this)
        {
            Destroy(this.gameObject);
            return;
        }
        else
        {
            instance = this;
        }
        DontDestroyOnLoad(this.gameObject);
    }

    void Update()
    { 
    
    }
}
